### ISSUE TITLE
Erreur dans le script sur le root de la compo TouchOSC

### ISSUE THREAD

**Issue by diffty** [MrFrangipane/osc-artnet-daemon#2]
Alors y a un souci avec le script Lua présent sur le root de la compo Touch :
Comme on rename DEVICE_NAME_TAB il le trouve plus au prochain passage sur la ligne 16

<img width="677" alt="image" src="https://github.com/user-attachments/assets/d510d825-2aae-4392-8a16-5b0e2731e7ea">
![telegram-cloud-photo-size-4-5821340412223276099-y](https://github.com/user-attachments/assets/ecf39ff1-dcca-448a-85e7-0985e0e0856b)

(je crois que ce système sera bientôt obsolète si j'en crois nos récentes discussions mais je garde le souci dans un coin pour ref)

**Comment by MrFrangipane** [comment]
Merci pour ce ticket :)

En effet ce hack n'est plus necessaire depuis que jai compris comment récuperer l'IP du client avec [python-osc](https://pypi.org/project/python-osc/)

**Comment by MrFrangipane** [comment]
Je le met en wontfix et closed car cela ne pose pas de probleme grave et sera remplacé par autre chose dans une version ultérieure :)
